spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coin-exchange?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    username: root
  application:
    name: authorization-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    port: 6379
    host: 127.0.0.1
server:
  port: 9999