#server:
#  port: 8082
#spring:
#  application:
#    name: coin-common
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/coin-exchange?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#    username: root
#    password: root
#  redis:
#    host: 127.0.0.1
#    port: 6379
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#      config:
#        enabled: false
##        file-extension: yaml
#    sentinel:
#      transport:
#        dashboard: 127.0.0.1:8080
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:/mapper/*Mapper.xml
#jetcache:
#  statIntervalMinutes: 15
#  areaInCacheName: false
#  local: #本地缓存  实现使用linkhasmap
#    default:
#      type: linkedhashmap
#      keyConvertor: fastjson
#  remote:
#    default:
#      type: redis
#      keyConvertor: fastjson
#      valueEncoder: kryo
#      valueDecoder: kryo
#      poolConfig:
#        minIdle: 5
#        maxIdle: 20
#        maxTotal: 50
#      host: ${spring.redis.host}
#      port: ${spring.redis.port}
#swagger2:
#  base-package: com.killb.controller
#  description: common测试
#  name: xiaozhang666
#  terms-of-service-url: www.killberos.cn
#  email: 111@qq.com
#  title: common测试
#  version: 2.0
#  url: github/yourZhang